version: '3.8'
services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: retail
      # So you don't have to use root, but you can if you like
      MYSQL_USER: retailadmin
      # You can use whatever password you like
      MYSQL_PASSWORD: password
      # Password for root access
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - database:/var/lib/mysql
    networks:
      - retail-network
  server:
    build:
      context: .
    ports:
      - 9090:9090
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/retail
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      JWT_EXPIRATION_IN_HOURS: 24
      JWT_SECRET: u2i3uu2dsggshgdsgdgdsgdshgds
    depends_on:
      db:
        condition: service_healthy
    networks:
      - retail-network

networks:
  retail-network:
    driver: bridge
volumes:
  database:

