apiVersion: v1
kind: Service
metadata:
  name: retail-backend-service
spec:
  selector:
    app: retail-backend
  ports:
    - name: grpc
      nodePort: 30171
      port: 9090
      targetPort: 9090
  type: NodePort